import InternalNav from "../InternalNav";
function Report() {
  return (
    <div className="md:flex md:flex-col  md:justify-end">
      <div className="mt-[62px] mb-[108px] sm:mt-8 sm:mb-[54px]">
        {/* Adjusted the heading to match server and client expectations */}
        <h3 className=" text-3xl font-normal font-weight-400 leading-10 sm:font-semibold">
          Category-Defining Technology
        </h3>
      </div>
      <div className="flex gap-[42.5px] sm:overflow-x-auto md:flex-col ">
        {/* Left */}
        <div className="w-[30%] md:w-full md:flex-col md:ml-10 sm:overflow-x-auto">
          <div className="flex flex-col gap-[29px] ">
            <h3 className=" text-3xl font-normal font-weight-400 leading-10">
              Customer Engagement and Sentiment Analysis
            </h3>
            <p>
              This report dives into the effectiveness of Proxima AI in
              enhancing customer engagement and sentiment. It provides a
              comprehensive analysis of customer interactions, sentiments
              expressed, and the impact on overall satisfaction. Using advanced
              sentiment analysis algorithms, the report showcases how Proxima
              AI&#39;s technology contributes to a positive customer experience
              by understanding and responding to customer emotions.
            </p>
            <small>↳ View the Full Report</small>
          </div>
          <div className=" flex flex-col gap-[29px] mt-[55px]">
            <h3 className=" text-3xl font-normal font-weight-400 leading-10">
              Data-Driven Decision-Making and Process Improvement
            </h3>
            <p>
              Focusing on the value derived from data generated by Proxima AI,
              this report showcases how organizations leverage insights to make
              informed decisions. It details how the platform&#39;s analytics
              contribute to internal and external process improvements, leading
              to better services for customers. The report provides concrete
              examples of data-driven strategies implemented by organizations
              using Proxima AI, emphasizing its role as a category-defining
              technology in shaping business processes.
            </p>
            <small>↳ View the Full Report</small>
          </div>
        </div>
        {/* Right */}
        <div className="flex gap-[20px] w-[67%] md:w-full md:flex-col md:ml-10">
          {/* change to 38 px for  large devices */}
          <div className="flex flex-col">
            <h3 className=" flex flex-col text-3xl font-normal font-weight-400 leading-10">
              Community Building and Experience Sharing Impact
            </h3>
            <p className="mt-[29px] sm:w-[350px]">
              Focusing on the creation of closely-knit customer communities,
              this report illustrates the impact of Proxima AI in fostering a
              sense of belonging among customers. It highlights how technology
              is employed to facilitate community building, enabling customers
              to share experiences with the company&#39;s products. The report
              measures the success of this approach in building a stronger
              customer base and brand loyalty.
            </p>
            <small className="mt-[29px]">
              — Ritu Jyoti, IDC &#39; s Group VP, AI and Automation
            </small>
            <small className="mt-[29px]">Read the Press Release</small>
          </div>
          <div className="flex flex-col ">
            <h3 className=" text-3xl font-normal font-weight-400 leading-10 ">
              Efficiency and Resource Optimization Metrics
            </h3>
            <p className="mt-[29px]">
              This report delves into the efficiency gains achieved by
              organizations using Proxima AI. It analyzes how the platform
              minimizes resource utilization while maximizing the handling of
              customer sentiments, feedback, complaints, and interests. Through
              detailed metrics and analytics, the report demonstrates how
              Proxima AI enables organizations to achieve optimal efficiency in
              managing customer interactions with minimal resources.
            </p>
            <small className="mt-[29px]">↳ View the Full Report</small>
          </div>
        </div>
      </div>
      {/* <InternalNav /> */}
    </div>
  );
}

export default Report;
